"""
Django settings for SongScope project.

Generated by 'django-admin startproject' using Django 5.0.6.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


from decouple import config

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

# Demo mode: serve the app as a single seeded Spotify account with NO per-user
# login (see config.auth.DemoModeAuthentication). Powers the public portfolio
# demo. Default False keeps the normal login flow intact for local dev.
DEMO_MODE = config('DEMO_MODE', default=False, cast=bool)
DEMO_USER_ID = config('DEMO_USER_ID', default=1, cast=int)

SPOTIFY_CLIENT_ID = config('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET = config('SPOTIFY_CLIENT_SECRET')
SPOTIFY_REDIRECT_URI = config('SPOTIFY_REDIRECT_URI')

# OpenAI API Configuration
OPENAI_API_KEY = config('OPENAI_API_KEY', default=None)

# Frontend URL
FRONTEND_URL = config('FRONTEND_URL')

# Clamp to False in production regardless of .env value
_raw_insecure = config('OAUTHLIB_INSECURE_TRANSPORT', 'False').lower() == 'true'
OAUTHLIB_INSECURE_TRANSPORT = _raw_insecure and DEBUG

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition


REST_FRAMEWORK = {
    # In demo mode, DemoModeAuthentication resolves every request to the seeded
    # demo user (no cookie). Session auth stays as a fallback / for local login.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        ['config.auth.DemoModeAuthentication'] if DEMO_MODE else []
    ) + [
        'config.auth.CsrfExemptSessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}


INSTALLED_APPS = [
    # Django built-in apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third-party apps
    'rest_framework',
    'corsheaders',
    
    # Local apps
    'apps.core.apps.CoreConfig',
    'apps.ai.apps.AiConfig',
    'apps.spotify.apps.SpotifyConfig',
    'apps.recommendations.apps.RecommendationsConfig',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Prod frontend origin(s): comma-separated https URLs (the Netlify site).
# Appended to the localhost defaults so dev + prod both work.
_extra_origins = [
    o.strip() for o in config('EXTRA_ALLOWED_ORIGINS', default='').split(',') if o.strip()
]
CORS_ALLOWED_ORIGINS += _extra_origins

CORS_ORIGIN_WHITELIST = [
    "http://localhost:3000"
]

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",  # Your Next.js frontend
] + _extra_origins
CSRF_USE_SESSIONS = False
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access to the cookie
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS

# Session settings
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING' if not DEBUG else 'INFO',
    },
}

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# Local dev uses SQLite; production sets DATABASE_URL (Render Postgres),
# parsed by dj-database-url.

import dj_database_url

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=not DEBUG and bool(config('DATABASE_URL', default='')),
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # collectstatic target for prod
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# URL Configuration
ROOT_URLCONF = "config.urls"

# Template Configuration
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI Application
WSGI_APPLICATION = "config.wsgi.application"

# Middleware Configuration
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # serve static files in prod
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "config.auth.DemoUserMiddleware",  # sets demo user (must follow AuthenticationMiddleware)
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
