# Generated by Django 5.1.3 on 2025-08-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
