# Generated by Django 5.0.6 on 2024-09-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songscope", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifytoken",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
