# Generated by Django 5.0.6 on 2024-10-29 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songscope", "0002_spotifytoken_expires_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("LIKE", "Like"),
                            ("DISLIKE", "Dislike"),
                            ("SKIP", "Skip"),
                            ("SAVE", "Save"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("track_features", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_weights", models.JSONField(default=dict)),
                ("genre_preferences", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="recommendationlog",
            old_name="recommended_at",
            new_name="timestamp",
        ),
        migrations.AddField(
            model_name="recommendationlog",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="audio_features",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="genres",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="recommendationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("RECOMMENDED", "Recommendation Generated"),
                    ("ERROR", "Error Occurred"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="recommendationlog",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="songscope.track",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="duration_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="popularity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="recommendationlog",
            index=models.Index(
                fields=["timestamp"], name="songscope_r_timesta_881b92_idx"
            ),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="songscope.track"
            ),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
