# Generated by Django 5.1.3 on 2025-08-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_userprofile_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="genres",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="feedback_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LIKE", "Like"),
                    ("DISLIKE", "Dislike"),
                    ("SAVE", "Save"),
                    ("SKIP", "Skip"),
                    ("PLAY", "Play"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userfeedback",
            name="track_features",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
