# Generated by Django 5.2.5 on 2026-04-29 12:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_track_genres_userfeedback_feedback_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationlog",
            name="track_popularity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recommendationlog",
            name="was_novel",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="DailyGem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("explanation", models.TextField(blank=True)),
                ("track_popularity", models.IntegerField(default=0)),
                ("was_liked", models.BooleanField(blank=True, null=True)),
                ("was_skipped", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.track"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
