# Generated by Django 5.2.5 on 2026-04-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_recommendationlog_track_popularity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailygem",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="dailygem",
            name="preview_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
