# Generated by Django 5.1.3 on 2025-08-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songscope", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cache_last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="recommendation_cache",
            field=models.JSONField(default=list),
        ),
    ]
