# Generated by Django 5.2.5 on 2026-05-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_dailygem_image_url_dailygem_preview_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationlog",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("playlist_mining", "Playlist Mining"),
                    ("artist_network", "Artist Network"),
                    ("genre_search", "Genre Search"),
                    ("related_artists", "Related Artists"),
                    ("contextual", "Contextual"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
