# Generated by Django 5.2.5 on 2026-05-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_recommendationlog_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifytoken",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
