# Generated by Django 5.2.5 on 2026-05-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_spotifytoken_refresh_token_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailygem",
            name="score_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="dailygem",
            name="score_total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailygem",
            name="taste_vector_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailygem",
            name="was_saved",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
