# Generated by Django 5.2.5 on 2026-06-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0008_dailygem_score_breakdown_score_total_was_saved_taste_vector_snapshot",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifytoken",
            name="access_token",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="spotifytoken",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
